name: blog
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dartz: 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 
  hive_flutter: 
  flutter_riverpod: 

dev_dependencies:
  build_runner: 
  flutter_gen_runner: 
  flutter_lints: 
  mocktail: 
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter_gen:
  output: lib/src/core/presentation/generated/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
    - family: Maruburi
      fonts:
        - asset: assets/fonts/maruburi/MaruBuri-Regular.ttf
        - asset: assets/fonts/maruburi/MaruBuri-Bold.ttf
          weight: 900
        - asset: assets/fonts/maruburi/MaruBuri-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/maruburi/MaruBuri-Light.ttf
          weight: 300
        - asset: assets/fonts/maruburi/MaruBuri-SemiBold.ttf
          weight: 700

    - family: Iropke
      fonts:
        - asset: assets/fonts/iropke/IropkeBatangM.ttf

    - family: NanumBarunPen
      fonts:
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenR.ttf
        - asset: assets/fonts/nanum-barun-pen/NanumBarunpenB.ttf
          weight: 700
