# Repo의 Actions 탭에 나타날 workflow 이름으로 필수 옵션 아님
name: CI/CD

# workflow 실행시키기 위한 Event 목록
on:
  # 하단 코드에 따라 main branch에 push event 발생시 workflow가 실행됨
  # 만약 브랜치 구분 없이 이벤트 지정하고자 한다면 단순히 아래와 같이 작성도
  # 가능
  # on: [push, pull_request]
  push:
    branches:
      - main
    pull_request:
      - main

    # 해당 옵션을 통해 사용자가 직접 actions 탭에서 worfklow를 실행시킬 수 있음
    # workflow_dispatch:

# 해당 Workflow의 하나 이상의 Job 목록
jobs:
  # Job 이름, flutter_test라는 이름으로 Job이 표시
  ci_cd:
    name: CI/CD on ${{ matrix.os }}
    # Runner가 실행되는 환경을 정의하는 부분
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]
        version: [2.10.3]
    # test Job 내의 step 목록
    steps:
      # Set up flutter
      - uses: actions/checkout@v2
        with:
          sdk: ${{ matrix.sdk }}
      - uses: subosito/flutter-action@v2
        with:
          flutter_version: ${{ matrix.version }}
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.working-directory }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .
        working-directory: ${{ env.working-directory }}
      
      - name: Analyze project source
        run: flutter analyze
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ env.working-directory }}

      - name: Deploy Flutter web app to github pages
        uses: jeremynac/flutter-gh-pages@beta